CREATE TABLE MEMBER(
	MNO			NUMBER(5) NOT NULL UNIQUE,
	MNAME		NVARCHAR2(5) NOT NULL,
	MSSN		NVARCHAR2(15) NOT NULL,
	MID			NVARCHAR2(10) PRIMARY KEY,
	MPW			NVARCHAR2(20) NOT NULL,
	MNN			NVARCHAR2(15) NOT NULL UNIQUE,
	MDATE		DATE NOT NULL );
	
CREATE SEQUENCE MEMBER_SEQ
	INCREMENT BY 1
	START WITH 1
	NOCACHE
	NOCYCLE;
	
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, '용상엽', '111111-1111111', 'admin', '7895', '관리자', SYSDATE);

SELECT * FROM MEMBER ORDER BY MNO ASC;

CREATE TABLE BOARD(
	BNO			NUMBER(5) PRIMARY KEY,
	BTITLE		NVARCHAR2(30) NOT NULL,
	BCONTENTS	NVARCHAR2(1000) NOT NULL,
	BWRITER		NVARCHAR2(15) NOT NULL CONSTRAINT BOARD_MNN_FK REFERENCES MEMBER(MNN),
	BDATE		DATE NOT NULL );

CREATE SEQUENCE BOARD_SEQ
	INCREMENT BY 1
	START WITH 1
	NOCACHE
	NOCYCLE;

INSERT INTO BOARD VALUES
(BOARD_SEQ.NEXTVAL, 'JDBC수업내용', '와 어렵다', '관리자', SYSDATE);
INSERT INTO BOARD VALUES
(BOARD_SEQ.NEXTVAL, 'JDBC수업내용1', '와 어렵다1', '관리자', SYSDATE);

SELECT * FROM BOARD ;
DROP SEQUENCE BOARD_SEQ;


CREATE TABLE BOARD_TRG AS SELECT * FROM BOARD;

CREATE TRIGGER TRG_BOARD_DELETE
	AFTER DELETE 
	ON BOARD
	FOR EACH ROW
BEGIN
		INSERT INTO BOARD_TRG VALUES (:OLD.BNO, :OLD.BTITLE, :OLD.BCONTENTS, :OLD.BWRITER, :OLD.BDATE);
END;

CREATE TABLE MEMBER_TRG AS SELECT * FROM MEMBER;


CREATE TRIGGER TRG_MEMBER_DELETE
	AFTER DELETE
	ON MEMBER
	FOR EACH ROW
BEGIN
		INSERT INTO MEMBER_TRG VALUES (:OLD.MNO, :OLD.MNAME, :OLD.MSSN, :OLD.MID, :OLD.MPW, :OLD.MNN, :OLD.MDATE);
END;




INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, '1', '111111-1111111', '123', '7895', '123', SYSDATE);
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, '2', '111111-1111111', '456', '7895', '456', SYSDATE);
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, '3', '111111-1111111', '12345', '7895', '12345', SYSDATE);

DELETE FROM MEMBER WHERE MID = '12345' ;
DROP TRIGGER TRG_MEMBER_DELETE;


TRUNCATE TABLE MEMBER_TRG;
SELECT * FROM MEMBER_TRG;
SELECT * FROM MEMBER;



DROP TRIGGER TRG_BOARD_DELETE;
DELETE FROM BOARD WHERE BNO = 10;

SELECT * FROM BOARD_TRG;
SELECT * FROM BOARD;
























